language: java
jdk: oraclejdk8

install: "./gradlew setupCIWorkspace --daemon"
script: "./gradlew build --daemon"
after_success: "./gradlew bintrayUpload --daemon"

notifications:
  email:
    recipients:
      - lousylynx12@gmail.com
    on_success: never
    on_failure: always